export default (loginConst = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  LOGOUT: 'USERS_LOGOUT',
  SET_TOKENS: 'USER_TOKENS_CHANGE',
  SET_ACCESS_TOKEN: 'USER_ACCESS_TOKEN_CHANGE'
});
