export default (notificationsConst = {
  GET_NOTIFICATIONS_REQUEST: 'USER_FEED_REQUEST',
  GET_NOTIFICATIONS_SUCCESS: 'USER_FEED_SUCCESS',
  GET_NOTIFICATIONS_FAILURE: 'USER_FEED_FAILURE',

  REFRESH_NOTIFICATIONS: 'REFRESH_NOTIFICATIONS'
});
