export default (profileConst = {
  PROFILE_REQUEST: 'USERS_PROFILE_REQUEST',
  PROFILE_SUCCESS: 'USERS_PROFILE_SUCCESS',
  PROFILE_FAILURE: 'USERS_PROFILE_FAILURE',

  PROFILE_POSTS_REQUEST: 'USERS_PROFILE_POSTS_REQUEST',
  PROFILE_POSTS_SUCCESS: 'USERS_PROFILE_POSTS_SUCCESS',
  PROFILE_POSTS_FAILURE: 'USERS_PROFILE_POSTS_FAILURE',

  PROFILE_LOGOUT: 'PROFILE_LOGOUT'
});
