export default (profileConst = {
  PROFILE_REQUEST: 'USERS_PROFILE_REQUEST',
  PROFILE_SUCCESS: 'USERS_PROFILE_SUCCESS',
  PROFILE_FAILURE: 'USERS_PROFILE_FAILURE',

  PROFILE_POSTS_REQUEST: 'USERS_PROFILE_POSTS_REQUEST',
  PROFILE_POSTS_SUCCESS: 'USERS_PROFILE_POSTS_SUCCESS',
  PROFILE_POSTS_FAILURE: 'USERS_PROFILE_POSTS_FAILURE',

  EDIT_PROFILE_REQUEST: 'EDIT_PROFILE_REQUEST',
  EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',
  EDIT_PROFILE_REMOVE_STORE: 'EDIT_PROFILE_REMOVE_STORE',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PROFILE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PROFILE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PROFILE_PASSWORD_FAILURE',

  SEND_CONTACT_REQUEST: 'SEND_CONTACT_REQUEST',
  SEND_CONTACT_SUCCESS: 'SEND_CONTACT_SUCCESS',
  SEND_CONTACT_FAILURE: 'SEND_CONTACT_FAILURE',

  ADD_POST_REQUEST: 'USER_PROFILE_ADD_POST_REQUEST',
  ADD_POST_SUCCESS: 'USER_PROFILE_ADD_POST_SUCCESS',
  ADD_POST_FAILURE: 'USER_PROFILE_ADD_POST_FAILURE',

  PROFILE_LOGOUT: 'PROFILE_LOGOUT'
});
