export default (registerConst = {
  SET_REGISTER_EMAIL: 'USER_REGISTER_EMAIL_SET',
  SET_REGISTER_PASSWORD: 'USER_REGISTER_PASSWORD_SET',

  VALIDATE_FIRST_REGISTER_SUCCESS: 'USER_FIRST_REGISTER_VALIDATION_SUCCESS',
  VALIDATE_FIRST_REGISTER_FAILURE: 'USER_FIRST_REGISTER_VALIDATION_FAILURE',

  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE'
});
