export default (searchConst = {
  SEARCH_TAGS_REQUEST: 'SEARCH_TAGS_REQUEST',
  SEARCH_TAGS_SUCCESS: 'SEARCH_TAGS_SUCCESS',
  SEARCH_TAGS_FAILURE: 'SEARCH_TAGS_FAILURE',

  SEARCH_USER_REQUEST: 'SEARCH_USER_REQUEST',
  SEARCH_USER_SUCCESS: 'SEARCH_USER_SUCCESS',
  SEARCH_USER_FAILURE: 'SEARCH_USER_FAILURE',

  SEARCH_TAG_POST_ITEMS_REQUEST: 'SEARCH_TAG_POST_ITEMS_REQUEST',
  SEARCH_TAG_POST_ITEMS_SUCCESS: 'SEARCH_TAG_POST_ITEMS_SUCCESS',
  SEARCH_TAG_POST_ITEMS_FAILURE: 'SEARCH_TAG_POST_ITEMS_FAILURE',

  REFRESH_TAG_POST_ITEMS: 'REFRESH_TAG_POST_ITEMS'
});
