export default (searchConst = {
  SEARCH_TAGS_REQUEST: 'SEARCH_TAGS_REQUEST',
  SEARCH_TAGS_SUCCESS: 'SEARCH_TAGS_SUCCESS',
  SEARCH_TAGS_FAILURE: 'SEARCH_TAGS_FAILURE',

  SEARCH_USER_REQUEST: 'SEARCH_USER_REQUEST',
  SEARCH_USER_SUCCESS: 'SEARCH_USER_SUCCESS',
  SEARCH_USER_FAILURE: 'SEARCH_USER_FAILURE'
});
